timeout: "3600s"  # 1 hour

substitutions:
  _COMMIT_SHA: "latest"

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-docker.pkg.dev/$PROJECT_ID/omega-prime-repo/omega-prime-agent:$_COMMIT_SHA'
    - '.'

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-docker.pkg.dev/$PROJECT_ID/omega-prime-repo/omega-prime-agent:$_COMMIT_SHA'
