steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/omega-prime-agent:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/omega-prime-agent:latest']
images:
- 'gcr.io/$PROJECT_ID/omega-prime-agent:latest'
