# Final and guaranteed build configuration for Omega Prime
# This configuration explicitly sets the logging mode within the build itself,
# bypassing any trigger-level configuration issues.

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/omega-prime-agent:$COMMIT_SHA', '.']

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/omega-prime-agent:$COMMIT_SHA']

# 3. Deploy the new container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'omega-prime-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/omega-prime-agent:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

# Make the new image available for deployment
images:
- 'gcr.io/$PROJECT_ID/omega-prime-agent:$COMMIT_SHA'
