# Simplified test configuration to verify permissions.
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['echo', 'Hello World! Build permissions are working!']
